server.port=8081

# H2 Database Configurations
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Settings (256-bit or greater key required for HS256)
# This is a sample base64-encoded secret key representing "supersecretkeyforcareonixauthservicemustbelongenough"
jwt.secret=c3VwZXJzZWNyZXRrZXlmb3JoaXJlY29ubmVjdGF1dGhzZXJ2aWNlbXVzdGJlbG9uZ2Vub3VnaA==
# 24 Hours = 86400000 ms
jwt.expiration=86400000
# 7 Days for Refresh Token = 604800000 ms
jwt.refresh-expiration=604800000

